import type { Spot } from "./types"

export const PLACEHOLDER_SPOTS: Spot[] = [
  {
    id: "placeholder-1",
    title: "The Optimist",
    description: "Upscale seafood with one of Atlanta's best patios. Perfect for date night with fresh oysters and craft cocktails.",
    venue: "The Optimist",
    url: "https://theoptimistrestaurant.com",
    category: "Dinner",
    costRange: "$$$",
    cityArea: "West Midtown",
    status: "Published",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&h=400&fit=crop",
    harmonysPick: true,
  },
  {
    id: "placeholder-2",
    title: "Monday Night Brewing — The Garage",
    description: "Chill vibes, great IPAs, and food trucks on weekends. Low-key happy hour spot in the O4W.",
    venue: "Monday Night Brewing",
    url: "https://mondaynightbrewing.com",
    category: "Drinks",
    costRange: "$",
    cityArea: "Old Fourth Ward",
    status: "Published",
    imageUrl: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=600&h=400&fit=crop",
    harmonysPick: false,
  },
  {
    id: "placeholder-3",
    title: "Painting with a Twist — Midtown",
    description: "BYOB paint nights that actually make for a fun date. No artistic skills required.",
    venue: "Painting with a Twist",
    url: "https://paintingwithatwist.com",
    category: "Activities",
    costRange: "$$",
    cityArea: "Midtown",
    status: "Published",
    imageUrl: "https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=600&h=400&fit=crop",
    harmonysPick: false,
  },
  {
    id: "placeholder-4",
    title: "Atlanta BeltLine Friday Night",
    description: "Walk the Eastside Trail at sunset, grab dinner at Ponce City Market, and catch live music along the way.",
    venue: "BeltLine Eastside Trail",
    url: "https://beltline.org",
    category: "Outdoor",
    costRange: "$",
    cityArea: "Inman Park",
    status: "Published",
    imageUrl: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&h=400&fit=crop",
    harmonysPick: false,
  },
  {
    id: "placeholder-5",
    title: "Ormsby's",
    description: "Bocce ball, shuffleboard, and excellent cocktails. The ultimate group date night in West Midtown.",
    venue: "Ormsby's",
    url: "https://ormsbys.com",
    category: "Activities",
    costRange: "$$",
    cityArea: "West Midtown",
    status: "Published",
    imageUrl: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=600&h=400&fit=crop",
    harmonysPick: false,
  },
  {
    id: "placeholder-6",
    title: "Atlanta Food & Wine Festival",
    description: "Annual tasting event showcasing the best of Southern cuisine. Limited tickets available.",
    venue: "Historic Fourth Ward Park",
    url: "https://atlfoodandwinefestival.com",
    category: "Events",
    costRange: "$$$",
    cityArea: "Old Fourth Ward",
    status: "Published",
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&h=400&fit=crop",
    harmonysPick: false,
  },
]
